#!/usr/bin/env python3
"""
Prism.js Language Generator for .zolo files

Generates prism-zolo.js dynamically from zlsp token patterns.
Run this script whenever zlsp patterns change to regenerate the language definition.

Usage:
    python3 generate_prism_zolo.py
    
Output:
    ../src/syntax/prism-zolo.js (Prism.js language definition)

Philosophy:
    Single Source of Truth (SSOT): zlsp defines tokens → Generator creates language
    Matches the Pygments generator pattern (generate_pygments_lexer.py)
"""

import os
import sys
from pathlib import Path
from datetime import datetime


def generate_file_header() -> str:
    """Generate file header with metadata."""
    return f'''/**
 * Prism.js Language Definition for .zolo files
 * 
 * AUTO-GENERATED by generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - Changes will be overwritten!
 * 
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * Source: zlsp token patterns (SSOT)
 * Maintainer: Run generate_prism_zolo.py to regenerate
 * 
 * Token patterns based on:
 * - zlsp/core/parser/parser_modules/line_parsers.py (key detection)
 * - zlsp/core/parser/parser_modules/token_emitters.py (value detection)
 * - zlsp/core/lsp_types.py (TokenType definitions)
 */

'''


def generate_prism_language() -> str:
    """
    Generate Prism.js language definition for .zolo syntax.
    
    Prism token mapping:
    - zlsp ROOT_KEY → Prism 'class-name' (pink/magenta)
    - zlsp UI_ELEMENT_KEY → Prism 'function' (blue/cyan)
    - zlsp NESTED_KEY → Prism 'property' (green)
    - zlsp ESCAPE_SEQUENCE → Prism 'string' + 'escape' (bright)
    - zlsp COMMENT → Prism 'comment' (dim gray)
    - zlsp TYPE_HINT → Prism 'type' (italic)
    - zlsp NUMBER → Prism 'number' (orange)
    - zlsp BOOLEAN → Prism 'boolean' (cyan)
    - zlsp STRING → Prism 'string' (default)
    """
    return '''(function (Prism) {
    /**
     * Zolo Language Definition
     * Declarative configuration syntax with dual-mode rendering (Terminal + GUI)
     */
    
    Prism.languages.zolo = {
        // ═══════════════════════════════════════════════════════════
        // COMMENTS
        // ═══════════════════════════════════════════════════════════
        // zlsp: TokenType.COMMENT
        'comment': {
            pattern: /#.*/,
            greedy: true
        },
        
        // ═══════════════════════════════════════════════════════════
        // ROOT-LEVEL KEYS (zlsp: TokenType.ROOT_KEY)
        // ═══════════════════════════════════════════════════════════
        // Pattern: ^[A-Z][a-zA-Z0-9_]*:
        // Examples: Page_Header:, Core_Concepts_Section:
        'root-key': {
            pattern: /^[ \\t]*[A-Z][a-zA-Z0-9_]*(?=\\s*(?:\\([^)]+\\))?[*!^~]?:)/m,
            alias: 'class-name',  // Pink/Magenta in most themes
            lookbehind: false
        },
        
        // ═══════════════════════════════════════════════════════════
        // DISPLAY EVENT KEYS (zlsp: TokenType.UI_ELEMENT_KEY)
        // ═══════════════════════════════════════════════════════════
        // Pattern: z[A-Z][a-zA-Z0-9]*:
        // Examples: zH1:, zText:, zMD:, zTable:, zUL:
        'display-event': {
            pattern: /\\bz[A-Z][a-zA-Z0-9]*(?=\\s*(?:\\([^)]+\\))?[*!]?:)/,
            alias: 'function',  // Blue/Cyan in most themes
        },
        
        // ═══════════════════════════════════════════════════════════
        // METADATA KEYS (zlsp: metadata attributes)
        // ═══════════════════════════════════════════════════════════
        // Pattern: _z[A-Z][a-zA-Z]+: or _data: or _transaction:
        // Examples: _zClass:, _zStyle:, _zId:, _data:
        'metadata': {
            pattern: /\\b(?:_z[A-Z][a-zA-Z]+|_data|_transaction)(?=:)/,
            alias: 'keyword',  // Yellow/Orange in most themes
        },
        
        // ═══════════════════════════════════════════════════════════
        // SPECIAL KEYS (zlsp: TokenType.ZMETA_KEY, etc.)
        // ═══════════════════════════════════════════════════════════
        // zMeta, zRBAC, ~zNavBar*
        'special-key': {
            pattern: /\\b(?:~?z(?:Meta|RBAC)|~zNavBar[a-zA-Z0-9_]*)(?=\\s*[*]?:)/,
            alias: 'builtin',  // Purple/Magenta in most themes
        },
        
        // ═══════════════════════════════════════════════════════════
        // PROPERTY KEYS (zlsp: TokenType.NESTED_KEY)
        // ═══════════════════════════════════════════════════════════
        // Pattern: [a-z][a-zA-Z0-9_]*:
        // Examples: label:, content:, color:, href*:
        'property': {
            pattern: /\\b[a-z][a-zA-Z0-9_]*(?=\\s*(?:\\([^)]+\\))?[*!]?:)/,
        },
        
        // ═══════════════════════════════════════════════════════════
        // TYPE HINTS (zlsp: TokenType.TYPE_HINT)
        // ═══════════════════════════════════════════════════════════
        // Examples: (int), (str), (bool)
        'type': {
            pattern: /\\([^)]+\\)/,
            alias: 'type',
        },
        
        // ═══════════════════════════════════════════════════════════
        // MODIFIERS (*, !, ^, ~)
        // ═══════════════════════════════════════════════════════════
        'modifier': {
            pattern: /[*!^~](?=:)/,
            alias: 'operator',
        },
        
        // ═══════════════════════════════════════════════════════════
        // PUNCTUATION (colons)
        // ═══════════════════════════════════════════════════════════
        'punctuation': /:/,
        
        // ═══════════════════════════════════════════════════════════
        // ESCAPE SEQUENCES (zlsp: TokenType.ESCAPE_SEQUENCE)
        // ═══════════════════════════════════════════════════════════
        // Unicode escapes: \\uXXXX, \\UXXXXXXXX
        'escape-sequence': {
            pattern: /\\\\[uU][0-9A-Fa-f]{4,8}|\\\\[nrtbf\\\\"']/,
            alias: 'string',
            inside: {
                'escape': /\\\\[uU]|\\\\[nrtbf\\\\"']/
            }
        },
        
        // ═══════════════════════════════════════════════════════════
        // BOOLEANS (zlsp: TokenType.BOOLEAN)
        // ═══════════════════════════════════════════════════════════
        'boolean': /\\b(?:true|false|True|False|yes|no|on|off)\\b/,
        
        // ═══════════════════════════════════════════════════════════
        // NULL VALUES (zlsp: TokenType.NULL)
        // ═══════════════════════════════════════════════════════════
        'null': /\\b(?:null|None)\\b/,
        
        // ═══════════════════════════════════════════════════════════
        // NUMBERS (zlsp: TokenType.NUMBER)
        // ═══════════════════════════════════════════════════════════
        'number': /-?\\d+(?:\\.\\d+)?/,
        
        // ═══════════════════════════════════════════════════════════
        // STRINGS (zlsp: TokenType.STRING)
        // ═══════════════════════════════════════════════════════════
        // Note: Zolo's string-first philosophy means most values are unquoted
        // This catches explicitly quoted strings
        'string': {
            pattern: /(?:"(?:\\\\.|[^\\\\"])*"|'(?:\\\\.|[^\\\\'])*')/,
            greedy: true
        }
    };
    
    // Register aliases
    Prism.languages.zolo['root-key'].alias = 'class-name';
    Prism.languages.zolo['display-event'].alias = 'function';
    Prism.languages.zolo['metadata'].alias = 'keyword';
    
}(Prism));
'''


def generate_language_file():
    """Generate the complete prism-zolo.js file."""
    output_dir = Path(__file__).parent.parent / 'src' / 'syntax'
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / 'prism-zolo.js'
    
    content = generate_file_header() + generate_prism_language()
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Generated: {output_path}")
    print(f"   Size: {len(content)} bytes")
    print(f"   Lines: {len(content.splitlines())}")
    print()
    print("🎨 Prism.js language ready for Bifrost syntax highlighting!")
    print()
    print("To test:")
    print("  1. Restart zCloud server")
    print("  2. Open zUI.zBreakpoints.zolo in browser")
    print("  3. Check code blocks for syntax highlighting")


def main():
    """Main entry point."""
    print("=" * 70)
    print("Prism.js Language Generator for .zolo files")
    print("=" * 70)
    print()
    print("Source: zlsp token patterns (SSOT)")
    print("Output: prism-zolo.js (Prism.js Bifrost highlighting)")
    print()
    
    generate_language_file()
    
    print()
    print("=" * 70)
    print("✅ Generation complete!")
    print("=" * 70)


if __name__ == '__main__':
    main()
