/**
 * Prism.js Language Definition for .zolo files
 * 
 * AUTO-GENERATED by generate_prism_zolo.py
 * DO NOT EDIT MANUALLY - Changes will be overwritten!
 * 
 * Generated: 2026-01-19 19:46:00
 * Source: zlsp token patterns (SSOT)
 * Maintainer: Run generate_prism_zolo.py to regenerate
 * 
 * Token patterns based on:
 * - zlsp/core/parser/parser_modules/line_parsers.py (key detection)
 * - zlsp/core/parser/parser_modules/token_emitters.py (value detection)
 * - zlsp/core/lsp_types.py (TokenType definitions)
 */

(function (Prism) {
    /**
     * Zolo Language Definition
     * Declarative configuration syntax with dual-mode rendering (Terminal + GUI)
     */
    
    Prism.languages.zolo = {
        // ═══════════════════════════════════════════════════════════
        // COMMENTS
        // ═══════════════════════════════════════════════════════════
        // zlsp: TokenType.COMMENT
        'comment': {
            pattern: /#.*/,
            greedy: true
        },
        
        // ═══════════════════════════════════════════════════════════
        // ROOT-LEVEL KEYS (zlsp: TokenType.ROOT_KEY)
        // ═══════════════════════════════════════════════════════════
        // Pattern: ^[A-Z][a-zA-Z0-9_]*:
        // Examples: Page_Header:, Core_Concepts_Section:
        'root-key': {
            pattern: /^[ \t]*[A-Z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!^~]?:)/m,
            alias: 'class-name',  // Pink/Magenta in most themes
            lookbehind: false
        },
        
        // ═══════════════════════════════════════════════════════════
        // DISPLAY EVENT KEYS (zlsp: TokenType.UI_ELEMENT_KEY)
        // ═══════════════════════════════════════════════════════════
        // Pattern: z[A-Z][a-zA-Z0-9]*:
        // Examples: zH1:, zText:, zMD:, zTable:, zUL:
        'display-event': {
            pattern: /\bz[A-Z][a-zA-Z0-9]*(?=\s*(?:\([^)]+\))?[*!]?:)/,
            alias: 'function',  // Blue/Cyan in most themes
        },
        
        // ═══════════════════════════════════════════════════════════
        // METADATA KEYS (zlsp: metadata attributes)
        // ═══════════════════════════════════════════════════════════
        // Pattern: _z[A-Z][a-zA-Z]+: or _data: or _transaction:
        // Examples: _zClass:, _zStyle:, _zId:, _data:
        'metadata': {
            pattern: /\b(?:_z[A-Z][a-zA-Z]+|_data|_transaction)(?=:)/,
            alias: 'keyword',  // Yellow/Orange in most themes
        },
        
        // ═══════════════════════════════════════════════════════════
        // SPECIAL KEYS (zlsp: TokenType.ZMETA_KEY, etc.)
        // ═══════════════════════════════════════════════════════════
        // zMeta, zRBAC, ~zNavBar*
        'special-key': {
            pattern: /\b(?:~?z(?:Meta|RBAC)|~zNavBar[a-zA-Z0-9_]*)(?=\s*[*]?:)/,
            alias: 'builtin',  // Purple/Magenta in most themes
        },
        
        // ═══════════════════════════════════════════════════════════
        // PROPERTY KEYS (zlsp: TokenType.NESTED_KEY)
        // ═══════════════════════════════════════════════════════════
        // Pattern: [a-z][a-zA-Z0-9_]*:
        // Examples: label:, content:, color:, href*:
        'property': {
            pattern: /\b[a-z][a-zA-Z0-9_]*(?=\s*(?:\([^)]+\))?[*!]?:)/,
        },
        
        // ═══════════════════════════════════════════════════════════
        // TYPE HINTS (zlsp: TokenType.TYPE_HINT)
        // ═══════════════════════════════════════════════════════════
        // Examples: (int), (str), (bool)
        'type': {
            pattern: /\([^)]+\)/,
            alias: 'type',
        },
        
        // ═══════════════════════════════════════════════════════════
        // MODIFIERS (*, !, ^, ~)
        // ═══════════════════════════════════════════════════════════
        'modifier': {
            pattern: /[*!^~](?=:)/,
            alias: 'operator',
        },
        
        // ═══════════════════════════════════════════════════════════
        // PUNCTUATION (colons)
        // ═══════════════════════════════════════════════════════════
        'punctuation': /:/,
        
        // ═══════════════════════════════════════════════════════════
        // ESCAPE SEQUENCES (zlsp: TokenType.ESCAPE_SEQUENCE)
        // ═══════════════════════════════════════════════════════════
        // Unicode escapes: \uXXXX, \UXXXXXXXX
        'escape-sequence': {
            pattern: /\\[uU][0-9A-Fa-f]{4,8}|\\[nrtbf\\"']/,
            alias: 'string',
            inside: {
                'escape': /\\[uU]|\\[nrtbf\\"']/
            }
        },
        
        // ═══════════════════════════════════════════════════════════
        // BOOLEANS (zlsp: TokenType.BOOLEAN)
        // ═══════════════════════════════════════════════════════════
        'boolean': /\b(?:true|false|True|False|yes|no|on|off)\b/,
        
        // ═══════════════════════════════════════════════════════════
        // NULL VALUES (zlsp: TokenType.NULL)
        // ═══════════════════════════════════════════════════════════
        'null': /\b(?:null|None)\b/,
        
        // ═══════════════════════════════════════════════════════════
        // NUMBERS (zlsp: TokenType.NUMBER)
        // ═══════════════════════════════════════════════════════════
        'number': /-?\d+(?:\.\d+)?/,
        
        // ═══════════════════════════════════════════════════════════
        // STRINGS (zlsp: TokenType.STRING)
        // ═══════════════════════════════════════════════════════════
        // Note: Zolo's string-first philosophy means most values are unquoted
        // This catches explicitly quoted strings
        'string': {
            pattern: /(?:"(?:\\.|[^\\"])*"|'(?:\\.|[^\\'])*')/,
            greedy: true
        }
    };
    
    // Register aliases
    Prism.languages.zolo['root-key'].alias = 'class-name';
    Prism.languages.zolo['display-event'].alias = 'function';
    Prism.languages.zolo['metadata'].alias = 'keyword';
    
}(Prism));
